name: Test Yarn build (frontend)

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'

jobs:
  yarn-build:
    name: Yarn install + build (frontend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack (Yarn)
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies with yarn
        working-directory: frontend
        run: |
          yarn install --immutable || yarn install

      - name: Build frontend
        working-directory: frontend
        run: |
          yarn build

      - name: Upload yarn.lock artifact
        if: ${{ success() && always() }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-yarn-lock
          path: frontend/yarn.lock
